openapi: 3.0.1
info:
  title: '@jupiterone/graph-servicenow'
  description: A graph conversion tool for ServiceNow
  x-cortex-git:
    github:
      repository: JupiterOne/graph-servicenow
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-servicenow'
